name: torchsurv
channels:
  - conda-forge
  - pytorch
dependencies:
  - python-build=1.2.2
  - pep517=0.13.0
  - numpy=1.26.4
  - pandas=2.2.0
  - pytorch=2.1.2
  - torchvision=0.16.2
  - lightning=2.1.3
  - loguru=0.7.2
  - scikit-learn=1.3.2
  - scikit-survival=0.22.2
  - lifelines=0.27.8
  - black=24.2.0
  - pylint=3.0.3
  - mypy=1.8.0
  - sphinx=7.2.6
  - sphinx-book-theme=1.1.2
  - sphinxcontrib-bibtex=2.6.2
  - myst-parser=2.0.0
  - nbsphinx=0.9.3
  - ipython=8.20.0
  - twine=4.0.2
  - scipy=1.12.0
  - sphinx-math-dollar=1.2.1
