name: Test-build Python Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.10

      - name: Build PyPI release
        run: uv build

      - name: Check PyPI release
        run: uvx twine check dist/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python-package
          path: dist
