name: "QC 🛠️"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Install dependencies
      run: uv sync --group dev --extra docs

    - name: Code QC
      run: uv run ./dev/codeqc.sh check

    - name: Tests
      run: |
        uv run ./dev/run-doctests.sh
        uv run pytest

    - name: Test-build docs
      run: |
        uv run ./dev/build-docs.sh
        tar czvf docs.tar.gz -C docs/_build/html .

    - name: 'Upload Docs Tarball'
      uses: actions/upload-artifact@v4
      with:
        name: docs.tar.gz
        path: docs.tar.gz
        retention-days: 5
