name: "Docs 📚"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.11

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Install dependencies
      run: uv sync --group dev --extra docs

    - name: Build docs
      run: uv run ./dev/build-docs.sh

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git checkout --orphan gh-pages
        cd docs/_build/html && tar czvf /tmp/docs.tar.gz * && cd ../../..
        git reset --hard
        git clean -fdx
        tar xvf /tmp/docs.tar.gz
        touch .nojekyll  # Prevents GitHub Pages from ignoring files that start with an underscore
        git add .
        git commit -m "Deploy GitHub Pages"
        git push -f origin gh-pages
